name: E2E Tests

# Gatilhos
on:
  workflow_dispatch:

jobs:
  tests: 
    # [config do so] (windows/linux/mac, chrome/firefox/edge, ...) 
    runs-on: ubuntu-latest
    # [variaveis] (variáveis de ambiente, chaves de acesso a plataformas, etc.)
    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000
    # [ações ou passsos]
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install
      
      - name: Iniciar servidor de Mock do REST API
        run: npm run mock-server &

      - name: Iniciar Aplicacao
        run: npm run server &

      - name: Executando testes E2E
        run: npx cypress run
